kind: PersistentVolumeClaim
apiVersion: v1
metadata: 
  name: "prometheus-alertmanager"
  namespace: monitoring
spec: 
  accessModes: 
  - ReadWriteMany
  resources: 
    requests: 
      storage: 10Gi
  volumeName: "prometheus-alertmanager-pv"
