kind: PersistentVolumeClaim
apiVersion: v1
metadata: 
  name: "prometheus-server"
  namespace: monitoring
spec: 
  accessModes: 
  - ReadWriteMany
  resources: 
    requests: 
      storage: 10Gi
  volumeName: "prometheus-server-pv"
