apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range
  namespace: wspark
spec:
  limits:
  - default:
      cpu: "2"
      memory: 512Mi
    defaultRequest:
      cpu: 100m
      memory: 256Mi
    type: Container
