apiVersion: v1
kind: PersistentVolume
metadata: 
  name: "springboot-demo-pv"
spec: 
  accessModes: 
  - ReadWriteMany
  capacity: 
    storage: 10Gi
  nfs:
    path: /data/nfs/wspark/springboot-sample
    server: 10.65.41.80
  persistentVolumeReclaimPolicy: Retain
