kind: PersistentVolumeClaim
apiVersion: v1
metadata: 
  name: "springboot-demo-pvc"
  namespace: wspark
spec: 
  accessModes: 
  - ReadWriteMany
  resources: 
    requests: 
      storage: 10Gi
  volumeName: "springboot-demo-pv"
