kind: PersistentVolumeClaim
apiVersion: v1
metadata: 
  name: "grafana"
  namespace: monitoring
spec: 
  accessModes: 
  - ReadWriteMany
  resources: 
    requests: 
      storage: 10Gi
  volumeName: "grafana-pv"
